[gcp_service_account]
type = "service_account"
project_id = "fotos-familia-lfve"
private_key_id = "efb8ac6df5badad2027ca954542a4ebfe9d10725"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDP65Um/qx8dp3s
2y+w2ZwpoXyRc0QU+d5AfrkNJbGEJyoRRBwEApi97Y1pJhm0Uf47RUtcsIKcmf2M
42mwhKqQQQH8Wj2d5xBJIRh7crdWVOYssHy20apZftQHjAEKPL2TNbFgn6mI1JOA
tmc8bHb1rvSKsjI6VxTx43oU1a3oP2j2M42ejFVoGQW6CQUoHkfzhii+cAzT5tBl
RWneAk70nQirTxIEkzobEVNDiH0QAqvdy57jHSXAwiR5bF0q9z+Wn5pdJh1HunpR
AYvE7KlQq7gWw4ZWLQS1Tm5mW1QZlh+02LZddhXuPo4j8JCSuYit3ZuGdoYTq96o
Pi5EGHi/AgMBAAECggEANPEwI+NCKVkMwmRXYukuHd2cOe8HPW4YXQTHeuUHq/ZK
/GWC2rSMjwP/d3A3qFYebZop49qgD18YlDjNzyAgzCV5a3fQ67WLzIssUDa4Hzfz
+hogT27YuPwV4iwQkbpArUzFMyzEfu5d9q67X8PgkJNxeiWAq6FD2InLKqX0J8gU
HkOfxknGZsJPn910zv5Ob+IRdVsXzHFTkL9d5BwbKo9AOQyCRFGN0P3Mel/MT4Z/
RgjoxGDeNJde8QaMGVsSrQSUUQfmht49tvL5HSaxWdaX/TrRTy3PD2zYcAV+DZDt
gnofhwZ4grvC88MtIaWfbuxLvqhKaQ8pJmWe3dqjPQKBgQDrZwENWKO6jE7sfMAB
8624llC8k+zCS61ryf9+cugSp0xuzw05LxDjM59FAhCYNEl/fXWKMDXHXsGrGbeC
MvR9hJEje8PE7AyNlfEceSnzOpqXNYqYkm4y9LidFsl2KvVYw+pYJrnpOvKLF9Kj
1C3U6713qBYsyy2olJW8pKwZEwKBgQDiHPsqhuJIFixhoUpxuI2X9bBQCDulqesb
0C1PkEnnJnUzLAakVSupaAXbeZaoO+vBT+0rAfXtA8b/zKZFoJqSBYzAqRCN/kHg
xv0ikSCJJRA70DRnEn7l7ABO3LbQbHQqMp5VumHiuUp/e+s5mM2qn0SGpiDxsFti
ZUJkg6/jJQKBgBlVa4KRMIWqBfBjeJJ9NAvyeVviG4/Jby9zfMCSAzHGuW4PcF/g
FdQtwQ0/LKQEtIg460Zk69S5+OO+D8a+TxuXAbus3SO7N5qhMWKcE4yumOZ/B5xl
3eA0AA4/3oyOEPttkjHMcSONiX64oJ2q/we0Gx7egwxtDUvgOcEkg7TrAoGAUtlF
mk5z6O/e8SLVERgLIYvPP3PUzx2UXMuJXqbCvWRU+xv9jwb6CYdo5gMGFbxm5Jzx
jJmaT27b4mxM3CQ9npVT/l+0BiMMZlzi8WB1qGqhKRlfqgiX4Iz5i+vJPFMQuUl0
xHqXVSiJSG7SQHdhnEvhIukKFySER2hMzGGH99UCgYAgsikrKDGrEfr8jSn2XffZ
pHZP3esEmx0syyLiDuVjkurTbJFx7RryfEktSbAnSPWdOExipFn1HoTtwfYI9J/N
dS2W98uWuZqe7HTLJm7hsJB9N9yR4Gx7u1oW7hFnXxkuI34dkwReI3t/VoT1TEo6
zre4nWCjX9TsmYMJ40Pm8A==
-----END PRIVATE KEY-----"""
client_email = "lector-final-lfve@fotos-familia-lfve.iam.gserviceaccount.com"
client_id = "109710648100528295991"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lector-final-lfve%40fotos-familia-lfve.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
